# Generated by Django 5.0 on 2023-12-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
